import Head from 'next/head';
import { Article } from 'src/components/article';
import { Nav } from 'src/components/nav';
import MainLayout from 'src/layouts';
import styles from 'src/styles/Home.module.scss';

const Home = (props) => {
  // 記事を取得できているか確認
  console.log(props.topArticles);
  return (
    <MainLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.contents}>
        <div className={styles.nav}>
          <nav>
            <Nav />
          </nav>
        </div>
        <div className={styles.blank} />
        <div className={styles.main}>
          <Article title="headlinens" articles={props.topArticles} />
        </div>
      </div>
    </MainLayout>
  );
};

export const getStaticProps = async () => {
  const pageSize = 10;
  const apiKey = '';
  const topRes = await fetch(
    `https://newsapi.org/v2/top-headlines?country=jp&pageSize=${pageSize}&apiKey=${apiKey}`
  );
  const topJson = await topRes.json();
  const topArticles = topJson?.articles;

  return {
    props: {
      topArticles,
    },
    revalidate: 60 * 10,
  };
};

export default Home;
